### ISSUE TITLE
reaching 8 connections: takes longer than before

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [mailchuck/PyBitmessage#186] opened 2016-03-24 16:12 UTC
I am using always the newest github code from here.
and connectivity worked quite fine. (1)

BUT: since the changes from Mar 21 or 22, 2016, getting 8 connections can take like 1h or more.
Before, it worked fast (1-5 mins) getting those 8.

Just tried with the new 0.5.8, but same problem.

I will send more details over the "Contact support" menu

(1)
P.S. Great work you are doing here, Peter!

**Comment by PeterSurda** [comment] 2016-03-24 17:00
Hello,

based on the report, this is caused by a reduced number of parallel connections when using a proxy (e.g. for Tor). There have been complaints that the defaults have the potential to overload Tor cirucuits, Tor exit nodes and behaviour like this is discouraged by the Tor project.

The commit in question is here: 225789d01f7b1c91cce48068f892313c3d3dab7f

The plan to fix this is to fully implement running PyBitmessage as a Tor hidden service. Currently, PyBitmessage already can connect to such nodes, it just cannot host them. There is a little work required for that. Then, Tor nodes can be configured to prefer hidden service nodes.

Combined with the issue that the clearnet "known nodes" currently contains tens of thousands of nodes that are not reachable (many of them probably completely fake). I'll try to change the behaviour that a node only is added if it is reachable. For clearnet, this is actually done by the connecting node, so it would have to do an extra check. For Tor, only the listening node knows its own onion address first, so it will have to check if it is reachable and then announce itself.

~~I need to think whether I'll do this within the 0.5.x cycle.~~ I decided to postpone this into 0.8 milestone. I would like to but I could use some help with Tor hidden services, and find out a way to check whether a node is connectable without relying on a centralised service.

PS thank you.

**Comment by PeterSurda** [comment] 2017-02-22 17:20
There were networking bugs where were now fixed, and hidden service is now also available. I think that's the main reason rather than the known nodes list (although that can be improved as well).

**Closed as completed by PeterSurda** 2017-02-22 17:20 UTC
Labels: enhancement
