### ISSUE TITLE
[Idea] Add "Rules" tab.

### ISSUE THREAD

**Issue by ghost** [mailchuck/PyBitmessage#192] opened 2016-04-16 00:20 UTC
Rules - like Thunderbird's Message filter function.

for example:
If body 'not contains' '--- PGP encrypted ---' then 'delete message immediately';
If subject 'is' 'command' AND body 'start with' 'reply:' then 'reply with message' 'hi';

**Comment by PeterSurda** [comment] 2016-04-16 06:16
Duplicate of #50

**Closed as completed by PeterSurda** 2016-04-16 06:16 UTC
