### ISSUE TITLE
idea: signatures

### ISSUE THREAD

**Issue by ghost** [mailchuck/PyBitmessage#48] opened 2015-10-13 09:28 UTC
identity aware ( and optional: recipent aware ) signatures which can be set in textfile config and/or GUI:

for example:
BM-long1 can include "signature 1", as I know this is the one I message people with I know,
BM-long2 shouldn't do this as it is a channel,
BM-long3 shouldn't do this as well because I message to channels/lists with this,
BM-long4 should include "signature 2" because for whatever reason,
etc.

**Comment by PeterSurda** [comment] 2015-11-11 08:32
Duplicate of Bitmessage#813

**Closed as completed by PeterSurda** 2015-11-11 08:32 UTC
Labels: enhancement
